# Site settings
title: Breguetes da Marisa - Arte com a mão
email: marisadeca@yahoo.com.br
description: "Artesanato para a sua casa feitos por Marisa Fernandes. Faça já sua encomenda das belíssimas Garrafas de vinho recicladas pintadas à mão ótimas para decoração da sua casa."
baseurl: ""
url: "http://www.breguetes.com.br"

# Build settings
markdown: kramdown
permalink: pretty